### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by ChrisWard316** [AddstarMC/geSuit#120]
I decided to restart my bungee from scratch and i done a completely fresh bungee install (Build #1489) and using your build gesuit build (#187)

This is the error:
`01:47:57 [WARNING] Exception encountered when loading plugin: geSuit
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
	at net.cubespace.geSuit.database.ConnectionPool.<init>(ConnectionPool.java:20)
	at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:32)
	at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:41)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more`

It doesn't create the gesuit folder. Any help would be appreciated i use your plugins all the time but i cant get this to load config files

**Comment by Narimm** [comment]
Try using the latest Waterfall build https://papermc.io/ci/job/Waterfall/ as oppose to BungeeCord
Waterfall is to Bungee as Paper is to Spigot.

Basically Waterfall shades in SLF4J Bungee doesnt.  I could shade it into gesuit and I might look at this but for now try this and let me know

**Comment by ChrisWard316** [comment]
Appears to be working, many thanks i guess i will use waterfall from now on
