### ISSUE TITLE
geSuit Spawn - Not returning to hub & other issues

### ISSUE THREAD

**Issue by ChrisWard316** [AddstarMC/geSuit#122]
My spawns.yml looks like this:

> `SpawnNewPlayerAtNewspawn: true
ForceAllPlayersToProxySpawn: true
`

This is the error in the bungee console:

`[15:20:28] [geSuit Pool Thread #5/INFO]: Loaded player chris_61 (cc0ef2ad-dde3-4b27-87ca-8cac6465caaf)
[15:20:28] [Netty Worker IO Thread #15/INFO]: Player chris_61 (cc0ef2ad-dde3-4b27-87ca-8cac6465caaf) connected from /82.41.16.213:54256
[15:20:28] [Netty Worker IO Thread #15/WARN] [geSuit]: Unable to find player named "chris_61" in onlinePlayers list!
[15:20:28] [Netty Worker IO Thread #15/INFO]: Warning! Teleport called but player is null!
[15:20:28] [Netty Worker IO Thread #15/ERROR]: java.lang.Exception: 
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at net.cubespace.geSuit.pluginmessages.TeleportToLocation.execute(TeleportToLocation.java:29)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at net.cubespace.geSuit.managers.SpawnManager.sendPlayerToProxySpawn(SpawnManager.java:49)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at net.cubespace.geSuit.listeners.SpawnListener.sendPlayerToHub(SpawnListener.java:17)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:434)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:543)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:20:28] [Netty Worker IO Thread #15/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
[15:20:28] [Netty Worker IO Thread #15/INFO]: [chris_61|/82.41.16.213:54256] <-> ServerConnector [vanilla] has connected
[15:20:28] [Netty Worker IO Thread #15/INFO]: » chris_61 has joined MCBuffalo!
[15:20:28] [geSuit Pool Thread #6/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@48d5f34e, id=44, owner=net.cubespace.geSuit.geSuit@2313052e, task=net.cubespace.geSuit.listeners.PlayerListener$$Lambda$392/1394598479@2051cd67, delay=0, period=0, running=true) encountered an exception
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4817) ~[?:1.8.0_241]
	at net.cubespace.geSuit.managers.GeoIPManager.lookup(GeoIPManager.java:123) ~[?:?]
	at net.cubespace.geSuit.listeners.PlayerListener.lambda$null$1(PlayerListener.java:132) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]`

**Comment by addstar** [comment]
Hi @ChrisWard316, it's really hard to read your error output. Can you update your issue description to use something like https://pastebin.com/ and also provide some more context about the issue.

Is this new behaviour? Are you using geSuit for the first time?

**Comment by ChrisWard316** [comment]
here it is as a pastebin (this still doesn't work but i found a work around bungee lets you force default server)

https://pastebin.com/xAYu7Zb9


There is also an issue with /spawn on server it doesn't work but if you do /ss or /ws it works. Very strange here is the error for that

https://pastebin.com/4A0Qf8Pb

**Comment by ChrisWard316** [comment]
Any updates @addstar, i really love using your plugin

**Comment by addstar** [comment]
@ChrisWard316 not sure what would be causing that, I will need to know more about your set up.

A few questions:

1. Can you provide exact versions/build numbers for bungee/gesuit/spigot, etc?
2. Is this a new/recent install or did you upgrade recently?
3. Is your bungee online or offline mode?
4. Does it still happen after a restart?
5. Does it happen every time for every player? Or just specific ones?

**Comment by ChrisWard316** [comment]
I have tried to look into this myself:

The second pastebin i showed you (https://pastebin.com/4A0Qf8Pb)

in maangers > spawnmaanger line 198
` 
    public void sendPlayerToSpawn(CommandSender sender) {
        Player p = ( Player ) sender;
        if(p.hasPermission("gesuit.spawns.spawn.bed")){
            try {
                p.teleport(p.getBedSpawnLocation());
            }catch(NullPointerException e){
            }

`

by reading that code i need a bed spawn set in order to be able to do /spawn. This is true i tested it i cant do /spawn without first having a bed set. Not sure how to fix really myself but i now see that is what is causing the issue. The first pastebin error i have noticed only happens when im op so i don't give myself OP

**Comment by ChrisWard316** [comment]
Any update?

**Comment by addstar** [comment]
@ChrisWard316 this is most likely fixed with our latest changes. Can you try the latest geSuit builds and let us know how it goes?
