### ISSUE TITLE
Starting of geSuit without DripReporterApi

### ISSUE THREAD

**Issue by normanfeltz** [AddstarMC/geSuit#125]
Hey,

Thanks for your work !

I want to use the last version of geSuit without DripReporterApi, but i have a error on startup !

`[18:12:32 WARN]: Exception encountered when loading plugin: geSuit
java.lang.NoClassDefFoundError: au/com/addstar/dripreporter/DripReporterApi
        at net.cubespace.geSuit.geSuit.enableDripReporterApi(geSuit.java:67) ~[?:?]
        at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:47) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
Caused by: java.lang.ClassNotFoundException: au.com.addstar.dripreporter.DripReporterApi
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 6 more`

I suggest to change the instanceof test :
https://github.com/AddstarMC/geSuit/blob/60026961c242c6cd109dea0c7b8645cf3f85c2a8/bungee/src/main/java/net/cubespace/geSuit/geSuit.java#L67

Thank you in advance !

Norman F.

**Comment by addstar** [comment]
@normanfeltz This should be fixed up in the latest build, can you try that and let us know?

**Comment by normanfeltz** [comment]
Hey,

Yes, it's fixed !

Thanks !

Norman F.
