### ISSUE TITLE
Players sometimes not re-added to online players list

### ISSUE THREAD

**Issue by MegaNarwhal** [AddstarMC/geSuit#67]
Under some circumstances, players are able to stay on the server when they are removed from geSuit's online players list:

```
22:25:34 [INFO] [DontL00kBack] <-> InitialHandler has connected
22:25:35 [INFO] [BungeePerms] Login by DontL00kBack (1d57b630-caa1-4488-a966-560a87eeb210)
22:25:35 [INFO] [DontL00kBack] disconnected with: You are already connected to this proxy!
22:25:35 [INFO] [BungeePerms] Adding default groups to DontL00kBack (1d57b630-caa1-4488-a966-560a87eeb210)
22:25:35 [INFO] Loaded player from cache DontL00kBack (1d57b630-caa1-4488-a966-560a87eeb210)
22:25:35 [INFO] Player DontL00kBack (1d57b630-caa1-4488-a966-560a87eeb210) connected from 24.224.89.182
22:25:35 [INFO] [DontL00kBack] <-> ServerConnector [survival] has connected
22:25:35 [INFO] [DontL00kBack] <-> DownstreamBridge <-> [survival] has disconnected
22:25:35 [INFO] - DontL00kBack
22:25:35 [INFO] Unloaded player DontL00kBack
22:25:35 [INFO] [DontL00kBack] -> UpstreamBridge has disconnected
22:25:36 [SEVERE] Aug 02, 2017 10:25:36 PM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event ServerConnectedEvent(player=DontL00kBack, server=net.md_5.bungee.ServerConnection@3e0bec89) to listener net.cubespace.geSuit.listeners.PlayerListener@5790cbcb
java.lang.NullPointerException
    at net.cubespace.geSuit.managers.PlayerManager.confirmJoin(PlayerManager.java:134)
    at net.cubespace.geSuit.listeners.PlayerListener.playerServerConnected(PlayerListener.java:52)
    at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:159)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:72)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:94)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:403)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)


22:25:44 [INFO] [Chat] DontL00kBack: this lag gona kill me
```

geSuit shows that the player leaves but they are still online, and exceptions are thrown subsequently when a player tries to do something using geSuit until they relog.

**Comment by Narimm** [comment]
Feel free to PR and post stacktraces in the future using pastebin...
