### ISSUE TITLE
Minecraft 1.13

### ISSUE THREAD

**Issue by Wolfbros** [AddstarMC/geSuit#74]
The Plguin does not work on spigot1.13. are you planning an update? 
Error message (Ban /Homes/Teleport/Warps/Spawn all the same error):

[Craft Scheduler Thread - 8/WARN]: [geSuiteSpawn] Plugin geSuiteSpawn v0.1.1-SNAPSHOT- generated an exception while executing task 146
java.lang.IllegalArgumentException: Channel must contain : separator
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.plugin.messaging.StandardMessenger.isOutgoingChannelRegistered(StandardMessenger.java:401) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:514) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.craftbukkit.v1_13_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1170) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
	at net.cubespace.geSuiteSpawn.tasks.PluginMessageTask.run(PluginMessageTask.java:26) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Narimm** [comment]
I have no words...but I agree 1.13 support is an issue.
