### ISSUE TITLE
Exception on boot

### ISSUE THREAD

**Issue by Artuto** [AddstarMC/geSuit#75]
Hi, I get this exception when the server boots up:

```java
[18:31:02] [main/INFO]: Starting geSuit
[18:31:02] [main/INFO]: Initialising Managers
[18:31:02] [main/WARN]: Exception encountered when loading plugin: geSuit
java.lang.ExceptionInInitializerError: null
	at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:27) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460) ~[?:1.8.0_181]
	at java.util.Properties.setProperty(Properties.java:166) ~[?:1.8.0_181]
	at com.mysql.jdbc.NonRegisteringDriver.parseURL(NonRegisteringDriver.java:808) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:321) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_181]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_181]
	at net.cubespace.geSuit.database.ConnectionPool.initialiseConnections(ConnectionPool.java:36) ~[?:?]
	at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:46) ~[?:?]
	... 5 more
```

Please help.

**Comment by Narimm** [comment]
....honestly 

1. Server Version?
2. Plugin Version?

Finally ...your using a development version which hasnt been released and is NON WORKING!

**Comment by Artuto** [comment]
Well, if it isnt from the jenkins page I dont know where I should get it then...

**Comment by Narimm** [comment]
Just cause jenkins built it....doesnt mean I released it...

**Comment by Narimm** [comment]
There is NO WORKING BUILD FOR 1.13

**Comment by Artuto** [comment]
All the backend servers are 1.13, waterfall is with the 1.13 support

**Comment by Artuto** [comment]
*1.12

**Comment by Narimm** [comment]
Well even better...the 1.0 builds are targetted at 1.13 and wont work with 1.12 anyway

**Comment by Artuto** [comment]
then where im supposed to download the plugin
 smh

**Comment by Narimm** [comment]
Perhaps you should use SpigotMC to get your releases, this is for bleeding edge and peopl who can compentantly diagnose and report bugs.

**Comment by Narimm** [comment]
The most recent build has a fix for this

**Comment by Artuto** [comment]
Not sure if its caused by the same issue but...

```java
[20:46:03 ERROR]: java.lang.NullPointerException
[20:46:03 ERROR]:       at net.cubespace.geSuit.database.Warps.getWarps(Warps.java:24)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.WarpsManager.loadWarpLocations(WarpsManager.java:18)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:52)
[20:46:03 ERROR]:       at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:27)
[20:46:03 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
[20:46:03 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[20:46:03 ERROR]: java.lang.NullPointerException
[20:46:03 ERROR]:       at net.cubespace.geSuit.database.Portals.getPortals(Portals.java:26)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.PortalManager.loadPortals(PortalManager.java:23)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:53)
[20:46:03 ERROR]:       at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:27)
[20:46:03 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
[20:46:03 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[20:46:03 ERROR]: java.lang.NullPointerException
[20:46:03 ERROR]:       at net.cubespace.geSuit.database.Spawns.getSpawn(Spawns.java:23)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.SpawnManager.loadSpawns(SpawnManager.java:25)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:54)
[20:46:03 ERROR]:       at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:27)
[20:46:03 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
[20:46:03 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[20:46:03 ERROR]: java.lang.NullPointerException
[20:46:03 ERROR]:       at net.cubespace.geSuit.database.Spawns.getSpawn(Spawns.java:23)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.SpawnManager.loadSpawns(SpawnManager.java:26)
[20:46:03 ERROR]:       at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:54)
[20:46:03 ERROR]:       at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:27)
[20:46:03 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283)
[20:46:03 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
[20:46:03 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)```

**Comment by Narimm** [comment]
The first error was a DB connection failure so the above is expected

**Comment by Narimm** [comment]
....what do you mean...on every restart.  Can you please provide a bit more background when you comment.. 

Everytime you restart a bungeecord the database is going to reinitialize and this problem would occur if the database is not connected.  I mean you shouldn't even run the build ..it will corrupt and screw up your servers.

**Comment by Artuto** [comment]
The database **is** configured and connected. The plugin created all the tables in the database....

**Comment by Narimm** [comment]
Which build ?

**Comment by Artuto** [comment]
up?

**Comment by Narimm** [comment]
In time.....my suggestion remains use an older build

**Comment by Artuto** [comment]
Well.. all download links on SpigotMC are down and the last non-1.13 build on the CI server doesnt even has a jar file...
