### ISSUE TITLE
Error Loading geSuit

### ISSUE THREAD

**Issue by ChrisWard316** [AddstarMC/geSuit#78]
I stupidly updated to your latest gesujit a few months ago even tho your previous one was working fine, now i cant connect to all my gesuit mysql data when i login to the servers. When loading the bungee plugin this is the error i get:

`15:29:32 [WARNING] Exception encountered when loading plugin: geSuit
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
	at net.cubespace.geSuit.database.ConnectionPool.<init>(ConnectionPool.java:20)
	at net.cubespace.geSuit.managers.DatabaseManager.<clinit>(DatabaseManager.java:32)
	at net.cubespace.geSuit.geSuit.onEnable(geSuit.java:34)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
15:29:32 [INFO] Enabled plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:bba5098:1358 by SpigotMC`

That is even on a fresh copy with the gesuit folder deleted, it won't create another folder

I'm on the latest Bungee Cord and geSuit-1.0.0-SNAPSHOT last successful build from 6 days ago, so my entire network is now down because no one can use any gesuit commands until i get this fixed

Any help in getting this sorted asap would be appreciated

**Comment by ChrisWard316** [comment]
Build 160 is the same error
